import { MenuItem, Deal } from './types';

export const PIZZA_1981_LOCATIONS = [
  {
    id: 'lahore',
    name: 'Lahore - Eden Mall',
    address: 'Shop No. G-9, Eden Mall, Eden Value Homes, Multan Road, Lahore',
    phone: '033 9911 1102',
    hours: '4:00 PM - 2:00 AM',
    deliveryFee: 200,
  },
];

const IMG = {
  pizza:    '/pizza-banner-1.png',
  burger:   '/pizza-banner-2.png',
  shawarma: '/pizza-banner-2.png',
  sandwich: '/pizza-banner-2.png',
  fries:    '/pizza-banner-1.png',
  drink:    '/pizza-banner-1.png',
  paratha:  '/pizza-banner-2.png',
};

export const PIZZA_1981_MENU: MenuItem[] = [
  { id: 'pizza-small',  name: 'Small Pizza (7")',   category: 'pizza', price: 750,  image: IMG.pizza,    description: 'Fresh homemade small pizza 7 inch' },
  { id: 'pizza-medium', name: 'Medium Pizza (11")', category: 'pizza', price: 1650, image: IMG.pizza,    description: 'Fresh homemade medium pizza 11 inch' },
  { id: 'pizza-large',  name: 'Large Pizza (13")',  category: 'pizza', price: 2150, image: IMG.pizza,    description: 'Fresh homemade large pizza 13 inch' },
  { id: 'pizza-family', name: 'Family Pizza (16")', category: 'pizza', price: 2650, image: IMG.pizza,    description: 'Family size pizza 16 inch' },
  { id: 'pizza-party',  name: 'Party Pizza (18")',  category: 'pizza', price: 3000, image: IMG.pizza,    description: 'Party size pizza 18 inch' },

  { id: 'burger-zinger',               name: 'Zinger Burger',                   category: 'burger', price: 500,  image: IMG.burger, description: 'Crispy fried chicken zinger burger' },
  { id: 'burger-zinger-cheese',        name: 'Zinger Cheese Burger',            category: 'burger', price: 560,  image: IMG.burger, description: 'Zinger burger with melted cheese' },
  { id: 'burger-zinger-cheese-olive',  name: 'Zinger + Cheese + Olive',         category: 'burger', price: 620,  image: IMG.burger, description: 'Zinger burger with cheese and olives' },
  { id: 'burger-zinger-full',          name: 'Zinger + Cheese + Olive + Kabab', category: 'burger', price: 700,  image: IMG.burger, description: 'Loaded zinger with cheese, olive and kabab' },
  { id: 'burger-classic-zinger',       name: 'Classic Zinger Burger',           category: 'burger', price: 500,  image: IMG.burger, description: 'Classic crispy zinger burger' },
  { id: 'burger-spicy-zinger',         name: 'Spicy Zinger Burger',             category: 'burger', price: 650,  image: IMG.burger, description: 'Extra spicy zinger burger' },
  { id: 'burger-double-zinger',        name: 'Double Zinger Burger',            category: 'burger', price: 680,  image: IMG.burger, description: 'Double patty zinger burger' },
  { id: 'burger-zinger-supreme',       name: 'Zinger Supreme',                  category: 'burger', price: 680,  image: IMG.burger, description: 'Supreme zinger burger with all toppings' },
  { id: 'burger-bbq-zinger',           name: 'BBQ Zinger',                      category: 'burger', price: 680,  image: IMG.burger, description: 'Zinger burger with BBQ sauce' },
  { id: 'burger-peri-peri',            name: 'Peri Peri Zinger',                category: 'burger', price: 680,  image: IMG.burger, description: 'Spicy peri peri zinger burger' },
  { id: 'burger-zinger-wrap',          name: 'Zinger Wrap',                     category: 'burger', price: 650,  image: IMG.burger, description: 'Zinger in a soft wrap' },
  { id: 'burger-fish-zinger',          name: 'Fish Zinger',                     category: 'burger', price: 650,  image: IMG.burger, description: 'Crispy fish zinger burger' },
  { id: 'burger-pizza-zinger',         name: 'Pizza Zinger',                    category: 'burger', price: 750,  image: IMG.burger, description: 'Pizza-style zinger burger' },
  { id: 'burger-mashroom-zinger',      name: 'Mashroom Zinger',                 category: 'burger', price: 800,  image: IMG.burger, description: 'Zinger burger with mushroom' },
  { id: 'burger-chicken-patti',        name: 'Chicken Patti Burger',            category: 'burger', price: 480,  image: IMG.burger, description: 'Chicken patti burger' },
  { id: 'burger-chicken-patti-cheese', name: 'Chicken Patti Cheese Burger',     category: 'burger', price: 550,  image: IMG.burger, description: 'Chicken patti burger with cheese' },
  { id: 'burger-beef-patti',           name: 'Beef Patti Burger',               category: 'burger', price: 600,  image: IMG.burger, description: 'Beef patti burger' },
  { id: 'burger-beef-patti-cheese',    name: 'Beef Patti Cheese Burger',        category: 'burger', price: 650,  image: IMG.burger, description: 'Beef patti burger with cheese' },

  { id: 'shawarma-chicken',        name: 'Chicken Shawarma',        category: 'shawarma', price: 350, image: IMG.shawarma, description: 'Tender grilled chicken shawarma' },
  { id: 'shawarma-chicken-cheese', name: 'Chicken Cheese Shawarma', category: 'shawarma', price: 450, image: IMG.shawarma, description: 'Chicken shawarma with melted cheese' },
  { id: 'shawarma-olive',          name: 'Olive Shawarma',          category: 'shawarma', price: 420, image: IMG.shawarma, description: 'Chicken shawarma with olives' },
  { id: 'shawarma-zinger',         name: 'Zinger Shawarma',         category: 'shawarma', price: 580, image: IMG.shawarma, description: 'Crispy zinger shawarma' },
  { id: 'shawarma-zinger-cheese',  name: 'Zinger Cheese Shawarma',  category: 'shawarma', price: 650, image: IMG.shawarma, description: 'Zinger shawarma with cheese' },
  { id: 'shawarma-beef',           name: 'Beef Shawarma',           category: 'shawarma', price: 680, image: IMG.shawarma, description: 'Grilled beef shawarma' },
  { id: 'shawarma-spicy',          name: 'Spicy Shawarma',          category: 'shawarma', price: 380, image: IMG.shawarma, description: 'Spicy chicken shawarma' },
  { id: 'shawarma-mixed',          name: 'Mixed Shawarma',          category: 'shawarma', price: 680, image: IMG.shawarma, description: 'Mixed chicken and beef shawarma' },
  { id: 'shawarma-fish',           name: 'Fish Shawarma',           category: 'shawarma', price: 680, image: IMG.shawarma, description: 'Crispy fish shawarma' },
  { id: 'shawarma-supreme',        name: 'Supreme Shawarma',        category: 'shawarma', price: 750, image: IMG.shawarma, description: 'Supreme loaded shawarma' },

  { id: 'sandwich-chicken',        name: 'Chicken Sandwich',         category: 'sandwich', price: 500, image: IMG.sandwich, description: 'Grilled chicken sandwich' },
  { id: 'sandwich-club',           name: 'Club Sandwich',            category: 'sandwich', price: 600, image: IMG.sandwich, description: 'Triple decker club sandwich' },
  { id: 'sandwich-beef',           name: 'Beef Sandwich',            category: 'sandwich', price: 600, image: IMG.sandwich, description: 'Beef patty sandwich' },
  { id: 'sandwich-chicken-tikka',  name: 'Chicken Tikka Sandwich',   category: 'sandwich', price: 600, image: IMG.sandwich, description: 'Spiced chicken tikka sandwich' },
  { id: 'sandwich-malai-boti',     name: 'Malai Boti Sandwich',      category: 'sandwich', price: 550, image: IMG.sandwich, description: 'Creamy malai boti sandwich' },
  { id: 'sandwich-egg',            name: 'Egg Sandwich',             category: 'sandwich', price: 300, image: IMG.sandwich, description: 'Classic egg sandwich' },
  { id: 'sandwich-chicken-fajita', name: 'Chicken Fajita Sandwich',  category: 'sandwich', price: 600, image: IMG.sandwich, description: 'Chicken fajita sandwich' },
  { id: 'sandwich-spicy-chicken',  name: 'Spicy Chicken Sandwich',   category: 'sandwich', price: 500, image: IMG.sandwich, description: 'Spicy chicken sandwich' },
  { id: 'sandwich-vegi',           name: 'Vegi Sandwich',            category: 'sandwich', price: 300, image: IMG.sandwich, description: 'Fresh vegetable sandwich' },
  { id: 'sandwich-fish',           name: 'Fish Sandwich',            category: 'sandwich', price: 650, image: IMG.sandwich, description: 'Crispy fish fillet sandwich' },
  { id: 'sandwich-supreme',        name: 'Chicken Supreme Sandwich', category: 'sandwich', price: 800, image: IMG.sandwich, description: 'Supreme loaded chicken sandwich' },

  { id: 'fries-small',  name: 'Fries (Small)', category: 'fries', price: 350, image: IMG.fries, description: 'Crispy golden fries small' },
  { id: 'fries-large',  name: 'Fries (Large)', category: 'fries', price: 500, image: IMG.fries, description: 'Crispy golden fries large' },
  { id: 'fries-loaded', name: 'Loaded Fries',  category: 'fries', price: 600, image: IMG.fries, description: 'Fries loaded with cheese and toppings' },
  { id: 'fries-pizza',  name: 'Pizza Fries',   category: 'fries', price: 700, image: IMG.fries, description: 'Fries with pizza toppings' },

  { id: 'drink-soft-345', name: 'Soft Drink (345ml)', category: 'drink', price: 100, image: IMG.drink, description: 'Cold soft drink 345ml can' },
  { id: 'drink-soft-500', name: 'Soft Drink (500ml)', category: 'drink', price: 150, image: IMG.drink, description: 'Cold soft drink 500ml bottle' },
  { id: 'drink-soft-1l',  name: 'Soft Drink (1L)',    category: 'drink', price: 180, image: IMG.drink, description: 'Cold soft drink 1 litre' },
  { id: 'drink-soft-15l', name: 'Soft Drink (1.5L)',  category: 'drink', price: 240, image: IMG.drink, description: 'Cold soft drink 1.5 litre' },

  { id: 'paratha-chicken',        name: 'Chicken Paratha Roll',        category: 'paratha', price: 480, image: IMG.paratha, description: 'Tender chicken paratha roll' },
  { id: 'paratha-chicken-cheese', name: 'Chicken Cheese Paratha Roll', category: 'paratha', price: 550, image: IMG.paratha, description: 'Chicken paratha with melted cheese' },
  { id: 'paratha-zinger',         name: 'Zinger Paratha Roll',         category: 'paratha', price: 650, image: IMG.paratha, description: 'Crispy zinger in paratha' },
  { id: 'paratha-zinger-cheese',  name: 'Zinger Cheese Paratha Roll',  category: 'paratha', price: 700, image: IMG.paratha, description: 'Zinger paratha with cheese and olive' },
  { id: 'paratha-beef',           name: 'Beef Paratha Roll',           category: 'paratha', price: 600, image: IMG.paratha, description: 'Grilled beef paratha roll' },
  { id: 'paratha-chapli',         name: 'Chapli Paratha Roll',         category: 'paratha', price: 650, image: IMG.paratha, description: 'Chapli kabab paratha roll' },
  { id: 'paratha-seekh-kabab',    name: 'Seekh Kabab Paratha Roll',    category: 'paratha', price: 650, image: IMG.paratha, description: 'Spiced seekh kabab paratha' },
  { id: 'paratha-aloo',           name: 'Aloo Paratha Roll',           category: 'paratha', price: 300, image: IMG.paratha, description: 'Classic aloo paratha roll' },
  { id: 'paratha-fish',           name: 'Fish Paratha Roll',           category: 'paratha', price: 650, image: IMG.paratha, description: 'Crispy fish paratha roll' },
];

export const PIZZA_1981_DEALS: Deal[] = [
  { id: 'deal-pizza-one',     name: 'Pizza Deal One',     image: '/pizza-banner-1.png', description: '2 Small Pizza (7") + Fries + Large Drink',                                         originalPrice: 2050,  discountedPrice: 1750, discountPercentage: 15, items: ['pizza-small','pizza-small','fries-small','drink-soft-15l'] },
  { id: 'deal-pizza-two',     name: 'Pizza Deal Two',     image: '/pizza-banner-1.png', description: '2 Medium Pizza (11") + 1 Fries + 2 Large Drink',                                   originalPrice: 4050,  discountedPrice: 3400, discountPercentage: 16, items: ['pizza-medium','pizza-medium','fries-small','drink-soft-15l','drink-soft-15l'] },
  { id: 'deal-pizza-three',   name: 'Pizza Deal Three',   image: '/pizza-banner-1.png', description: '2 Large Pizza (13") + 1 Fries + 2 Large Drink',                                   originalPrice: 5050,  discountedPrice: 4200, discountPercentage: 17, items: ['pizza-large','pizza-large','fries-small','drink-soft-15l','drink-soft-15l'] },
  { id: 'deal-pizza-four',    name: 'Pizza Deal Four',    image: '/pizza-banner-1.png', description: '2 Family Pizza (16") + 2 Fries + 2 Drink 1.5 Liter',                              originalPrice: 6400,  discountedPrice: 5150, discountPercentage: 20, items: ['pizza-family','pizza-family','fries-small','fries-small','drink-soft-15l','drink-soft-15l'] },
  { id: 'deal-pizza-five',    name: 'Pizza Deal Five',    image: '/pizza-banner-1.png', description: '2 Party Pizza (18") + 2 Large Drink 1.5 Ltr',                                     originalPrice: 7100,  discountedPrice: 5650, discountPercentage: 20, items: ['pizza-party','pizza-party','drink-soft-15l','drink-soft-15l'] },
  { id: 'deal-special-one',   name: 'Special Deal One',   image: '/pizza-banner-2.png', description: 'Large Pizza (13") + Zinger Burger + Fries + Large Drink',                         originalPrice: 3450,  discountedPrice: 2550, discountPercentage: 26, items: ['pizza-large','burger-zinger','fries-small','drink-soft-15l'] },
  { id: 'deal-special-two',   name: 'Special Deal Two',   image: '/pizza-banner-2.png', description: '2 Large Pizza (13") + 2 Zinger Burger + 2 Fries + 2 Large Drink',                originalPrice: 6700,  discountedPrice: 4999, discountPercentage: 25, items: ['pizza-large','pizza-large','burger-zinger','burger-zinger','fries-small','fries-small','drink-soft-15l','drink-soft-15l'] },
  { id: 'deal-special-three', name: 'Special Deal Three', image: '/pizza-banner-2.png', description: '2 Medium Pizza (11") + 2 Zinger Burger + Shawarma + 2 Large Drink',              originalPrice: 5700,  discountedPrice: 4550, discountPercentage: 20, items: ['pizza-medium','pizza-medium','burger-zinger','burger-zinger','shawarma-chicken','drink-soft-15l','drink-soft-15l'] },
  { id: 'deal-couple',        name: 'Couple Deal',        image: '/pizza-banner-1.png', description: '1 Small Pizza (7") + 1 Zinger Burger + 1 Drink Half Liter',                      originalPrice: 1520,  discountedPrice: 1250, discountPercentage: 18, items: ['pizza-small','burger-zinger','drink-soft-500'] },
  { id: 'deal-family-one',    name: 'Family Deal One',    image: '/pizza-banner-2.png', description: '1 Large Pizza (13") + 2 Zinger Burger + 1 Fries + 1 Large Drink',                originalPrice: 4000,  discountedPrice: 2999, discountPercentage: 25, items: ['pizza-large','burger-zinger','burger-zinger','fries-small','drink-soft-15l'] },
  { id: 'deal-family-two',    name: 'Family Deal Two',    image: '/pizza-banner-2.png', description: '2 Large Pizza (13") + 2 Zinger Burger + 2 Fries + 2 Large Drink',                originalPrice: 6700,  discountedPrice: 4999, discountPercentage: 25, items: ['pizza-large','pizza-large','burger-zinger','burger-zinger','fries-small','fries-small','drink-soft-15l','drink-soft-15l'] },
  { id: 'deal-big',           name: 'Big Deal',           image: '/pizza-banner-1.png', description: '3 Large Pizza (13") + 3 Zinger Burger + 3 Fries + 3 Large Drink',                originalPrice: 10050, discountedPrice: 7999, discountPercentage: 20, items: ['pizza-large','pizza-large','pizza-large','burger-zinger','burger-zinger','burger-zinger','fries-small','fries-small','fries-small','drink-soft-15l','drink-soft-15l','drink-soft-15l'] },
  { id: 'deal-office',        name: 'Office Deal',        image: '/pizza-banner-2.png', description: '2 Family Pizza (16") + 4 Zinger Burger + 4 Fries + 4 Large Drink',               originalPrice: 10100, discountedPrice: 7999, discountPercentage: 21, items: ['pizza-family','pizza-family','burger-zinger','burger-zinger','burger-zinger','burger-zinger','fries-small','fries-small','fries-small','fries-small','drink-soft-15l','drink-soft-15l','drink-soft-15l','drink-soft-15l'] },
  { id: 'deal-party',         name: 'Party Deal',         image: '/pizza-banner-1.png', description: '4 Large Pizza (13") + 5 Zinger Burger + 4 Large Fries + 5 Large Drink',          originalPrice: 13040, discountedPrice: 9999, discountPercentage: 23, items: ['pizza-large','pizza-large','pizza-large','pizza-large','burger-zinger','burger-zinger','burger-zinger','burger-zinger','burger-zinger','fries-large','fries-large','fries-large','fries-large','drink-soft-15l','drink-soft-15l','drink-soft-15l','drink-soft-15l','drink-soft-15l'] },
  { id: 'deal-student',       name: 'Student Deal',       image: '/pizza-banner-2.png', description: '1 Medium Pizza (11") + 1 Zinger Burger + 1 Fries + 2 Small Drinks',             originalPrice: 2810,  discountedPrice: 1999, discountPercentage: 29, items: ['pizza-medium','burger-zinger','fries-small','drink-soft-345','drink-soft-345'] },
  { id: 'deal-friends',       name: 'Friends Deal',       image: '/pizza-banner-1.png', description: '2 Medium Pizza (11") + 2 Zinger Burger + 2 Large Drink',                         originalPrice: 5700,  discountedPrice: 4650, discountPercentage: 18, items: ['pizza-medium','pizza-medium','burger-zinger','burger-zinger','drink-soft-15l','drink-soft-15l'] },
  { id: 'deal-kids',          name: 'Kids Deal',          image: '/pizza-banner-2.png', description: '1 Small Pizza (7") + 1 Patty Burger + 2 Small Fries',                            originalPrice: 2300,  discountedPrice: 1599, discountPercentage: 30, items: ['pizza-small','burger-chicken-patti','fries-small','fries-small'] },
  { id: 'deal-zinger-one',    name: 'Zinger Deal One',    image: '/pizza-banner-2.png', description: '2 Zinger Burger + 1 Fries + 2 Small Drink (345ml)',                              originalPrice: 2050,  discountedPrice: 1600, discountPercentage: 22, items: ['burger-zinger','burger-zinger','fries-small','drink-soft-345','drink-soft-345'] },
  { id: 'deal-zinger-two',    name: 'Zinger Deal Two',    image: '/pizza-banner-2.png', description: '3 Zinger Burger + 3 Fries + 3 Small Drink 345ml',                                originalPrice: 3600,  discountedPrice: 2900, discountPercentage: 19, items: ['burger-zinger','burger-zinger','burger-zinger','fries-small','fries-small','fries-small','drink-soft-345','drink-soft-345','drink-soft-345'] },
  { id: 'deal-paratha-one',   name: 'Paratha Deal One',   image: '/pizza-banner-2.png', description: '2 Paratha Roll + 1 Fries + 1 Small Drinks',                                      originalPrice: 1410,  discountedPrice: 1150, discountPercentage: 18, items: ['paratha-chicken','paratha-chicken','fries-small','drink-soft-345'] },
  { id: 'deal-paratha-two',   name: 'Paratha Deal Two',   image: '/pizza-banner-2.png', description: '3 Paratha Roll + 2 Fries + 3 Small Drink 345ml',                                 originalPrice: 2740,  discountedPrice: 2150, discountPercentage: 22, items: ['paratha-chicken','paratha-chicken','paratha-chicken','fries-small','fries-small','drink-soft-345','drink-soft-345','drink-soft-345'] },
  { id: 'deal-all-in-one',    name: 'All In One Deal',    image: '/pizza-banner-1.png', description: '1 Small Pizza + 1 Zinger Burger + 1 Shawarma + 1 Paratha Roll + 4 Small Drink',  originalPrice: 2630,  discountedPrice: 2150, discountPercentage: 18, items: ['pizza-small','burger-zinger','shawarma-chicken','paratha-chicken','drink-soft-345','drink-soft-345','drink-soft-345','drink-soft-345'] },
  { id: 'deal-is-deal',       name: 'Deal Is Deal',       image: '/pizza-banner-1.png', description: '1 Medium Pizza + 1 Zinger Burger + 1 Shawarma + 1 Paratha Roll + 4 Small Drink', originalPrice: 3530,  discountedPrice: 2750, discountPercentage: 22, items: ['pizza-medium','burger-zinger','shawarma-chicken','paratha-chicken','drink-soft-345','drink-soft-345','drink-soft-345','drink-soft-345'] },
  { id: 'deal-eat-big',       name: 'Eat Big Pay Small',  image: '/pizza-banner-1.png', description: '2 Small Pizza + 2 Zinger Burger + 2 Shawarma + 1 Paratha Roll + 4 Small Drink',  originalPrice: 4860,  discountedPrice: 3800, discountPercentage: 22, items: ['pizza-small','pizza-small','burger-zinger','burger-zinger','shawarma-chicken','shawarma-chicken','paratha-chicken','drink-soft-345','drink-soft-345','drink-soft-345','drink-soft-345'] },
];

export const MENU_CATEGORIES = [
  { id: 'all',      label: 'All',           icon: 'list'      },
  { id: 'pizza',    label: 'Pizzas',        icon: 'pizza'     },
  { id: 'burger',   label: 'Burgers',       icon: 'burger'    },
  { id: 'shawarma', label: 'Shawarma',      icon: 'drumstick' },
  { id: 'sandwich', label: 'Sandwiches',    icon: 'sandwich'  },
  { id: 'fries',    label: 'Fries',         icon: 'cup'       },
  { id: 'drink',    label: 'Drinks',        icon: 'cup'       },
  { id: 'paratha',  label: 'Paratha Rolls', icon: 'bread'     },
  { id: 'deal',     label: 'Deals',         icon: 'tag'       },
];

export const SERVICE_AREAS: { name: string; deliveryFee: number }[] = [
  { name: 'Eden Value Homes',                      deliveryFee: 100 },
  { name: 'Jazac City',                            deliveryFee: 120 },
  { name: 'Park View City',                        deliveryFee: 150 },
  { name: 'EME DHA Lahore',                        deliveryFee: 200 },
  { name: 'Rail Town',                             deliveryFee: 130 },
  { name: 'P & Society',                           deliveryFee: 140 },
  { name: 'Green Fort 2',                          deliveryFee: 110 },
  { name: 'Chung',                                 deliveryFee: 180 },
  { name: 'Izmir Town',                            deliveryFee: 120 },
  { name: 'Iqbal Avenue Housing Society',          deliveryFee: 130 },
  { name: 'Green View Society',                    deliveryFee: 120 },
  { name: 'Chaman Park',                           deliveryFee: 100 },
  { name: 'Rajboot Town',                          deliveryFee: 150 },
  { name: 'Muhafiz Town',                          deliveryFee: 160 },
  { name: 'PASCO Society',                         deliveryFee: 140 },
  { name: 'Lahore Canal Bank Phase 1',             deliveryFee: 170 },
  { name: 'Eden Canal Villas',                     deliveryFee: 100 },
  { name: 'Etihad Town',                           deliveryFee: 130 },
  { name: 'Excise and Taxation Society',           deliveryFee: 150 },
  { name: 'Doctors Society',                       deliveryFee: 140 },
  { name: 'Green Fort 1',                          deliveryFee: 110 },
  { name: 'Executive Apartments',                  deliveryFee: 120 },
  { name: 'Atchison Colony',                       deliveryFee: 200 },
  { name: 'Sultan Town',                           deliveryFee: 160 },
  { name: 'Ali Town',                              deliveryFee: 150 },
  { name: 'Nawab Town',                            deliveryFee: 170 },
  { name: 'Abdalians Cooperative Housing Society', deliveryFee: 180 },
  { name: 'Johar Town B Block',                    deliveryFee: 130 },
  { name: 'Judicial Colony Phase 1',               deliveryFee: 140 },
  { name: 'Canal Berg Society',                    deliveryFee: 160 },
  { name: 'Canal View Society',                    deliveryFee: 150 },
  { name: 'Johar Town J Block',                    deliveryFee: 130 },
  { name: 'Johar Town J3 Block',                   deliveryFee: 130 },
  { name: 'Johar Town H Block',                    deliveryFee: 130 },
  { name: 'Johar Town G1 Block',                   deliveryFee: 130 },
  { name: 'Johar Town Q Block',                    deliveryFee: 140 },
  { name: 'Johar Town P Block',                    deliveryFee: 140 },
  { name: 'Johar Town R1 Block',                   deliveryFee: 140 },
  { name: 'Johar Town R2 Block',                   deliveryFee: 140 },
  { name: 'Johar Town R3 Block',                   deliveryFee: 140 },
  { name: 'Johar Town D1 Block',                   deliveryFee: 130 },
  { name: 'Punjab University New Campus',          deliveryFee: 160 },
  { name: 'Ghosha-e-Ahbab Phase 2',               deliveryFee: 120 },
  { name: 'Mansoorab',                             deliveryFee: 170 },
  { name: 'Mustafa Town',                          deliveryFee: 180 },
  { name: 'Azam Garden',                           deliveryFee: 190 },
  { name: 'Hanjarwal',                             deliveryFee: 200 },
  { name: 'Ahbab Colony',                          deliveryFee: 120 },
  { name: 'Gulzar Colony',                         deliveryFee: 130 },
  { name: 'Saif Town',                             deliveryFee: 150 },
  { name: 'Gulshan Town',                          deliveryFee: 140 },
  { name: 'Munir Garden',                          deliveryFee: 130 },
  { name: 'Maraghazar Colony',                     deliveryFee: 120 },
  { name: 'Ghosia Park',                           deliveryFee: 110 },
];
